#include <stdio.h>
#include <stdlib.h>
#include "util.h"

/*
Function: generate_sequence
----------------------------------
It does: a recursive function to generate and return the sequence

xs: first element of sequence
currentlen: length of the sequence in the time of the function called
seqlen: length of the sequence
*seq: array of the sequence
*/
void generate_sequence(int xs, int currentlen, int seqlen, int *seq);

/*
Function: check_loop_iterative
----------------------------------
It does: a recursive function such that given any function and a starting integer check if the sequence ends up in a loop 

void *f: generate_sequence function
xs: first element of sequence
seqlen: length of the sequence
*loop: array of the loop
*looplen: length of the loop in the time of the function called
*/
void check_loop_iterative(void (*f)(), int xs, int seqlen, int *loop,int *looplen);

/*
Function: has_loop
----------------------------------
It does: Check the sequence if it has a loop

*arr: array of the sequence
n: length of the sequence
looplen: length of the loop
*ls: loop's first index
*le: the index of last loop started

returns: it will return 1 if a loop exists, 0 otherwise
*/
int has_loop(int *arr, int n, int looplen, int *ls, int *le);

/*
Function: hist_of_firstdigits
----------------------------------
It does: a recursive function that calculates the histogram of the first digits of the sequence generated by a given function 

void *f: generate_sequence function
xs: first element of sequence
seqlen: length of the sequence
*h: it is the histogram of the first digits of the numbers that appear in the sequence. it's an array
digit: digit of the histogram
*/
void hist_of_firstdigits(void (*f)(), int xs, int seqlen, int *h, int digit);

void generate_sequence(int xs, int currentlen, int seqlen, int *seq){
    //If the number is divisible by 2, divide by 2, otherwise do the other operation
    if(currentlen < seqlen){
       *(seq+currentlen)  = xs;
       if(xs%2 == 0) xs /= 2;
       else xs = xs * 3 + 1;
       generate_sequence(xs,currentlen+1,seqlen,seq);
    }
}

void check_loop_iterative(void (*f)(), int xs, int seqlen, int *loop,int *looplen){
    int ls,le;
    int check;
    int *seq;
    //allocate memory
    seq = (int*)malloc(sizeof(int) * seqlen);
    //call generate_sequence function
    f(xs,0,seqlen,seq);
    //print the sequence one time
    if(*looplen == seqlen/2) {
        printf("Sequence: {%d",seq[0]);
        for(int i = 1;i < seqlen;i++) printf(", %d",seq[i]);
        printf("}\n");
        printf("\n");
    }
    check = has_loop(seq,seqlen,*looplen,&ls,&le);
    if(check == 0 && *looplen > 2){
        //Free the memory,decrease looplen by -1 and call function again
        free(seq);
        *looplen-=1;
        check_loop_iterative(f, xs, seqlen, loop,looplen);
    }
    else if(check == 1){
        printf("Loop detected with a length of %d.\n",*looplen);
        printf("The indexes of the loop's first occurance: %d (first digit), %d (last digit)\n",ls,le);
        for(int i = 0;i < *looplen;i++){
            *(loop + i) = seq[ls + i];
        }
        free(seq);
    }
    else{
        *looplen = -1;
        free(seq);
    }
}

int has_loop(int *arr, int n, int looplen, int *ls, int *le){
    printf("Checking if there is a loop of length %d...\n",looplen);
    int check = 0;
    int i = 0,k = 0,j;
    while(i < (n - (n%looplen))/looplen - 1){
        check = 1;
        //Check the first loop number and last numbers of arr. If they are not equal set check to 0.
        for(j = 0;j < looplen;j++){
           if(*(arr + j + i*looplen + (n%looplen)) != *(arr + n - looplen + j)) check = 0;
        }
      if(check == 0) i++;
      else {//If there is a loop set *ls and *le to indexs
          *ls = i*looplen + (n%looplen);
          *le = i*looplen + (n%looplen) + looplen - 1;
           i = n;
      }
    }
    return check;
}

void hist_of_firstdigits(void (*f)(), int xs, int seqlen, int *h, int digit){
    int *seq;
    int a = 0;
    int i;
    // allocate memory and generate sequnce
    seq = (int*)malloc(sizeof(int) * seqlen);
    f(xs,0,seqlen,seq);
    //find first digits of numbers
    for(i = 0;i < seqlen;i++){
        while(*(seq + i) >= 10){
        *(seq + i) = *(seq + i) / 10;
        }
        if(*(seq + i) == digit) ++a;//find how many times of this digit we have
    }
    *(h + digit - 1) = a;
    if(digit != 9){
       hist_of_firstdigits(generate_sequence, xs, seqlen, h, digit + 1);
    }else free(seq);
}